"""initial migration

Revision ID: 04104cb5e8bd
Revises: 
Create Date: 2025-05-15 17:09:58.567561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04104cb5e8bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('agency_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('agency_name')
    )
    op.create_table('projects',
    sa.Column('project_name', sa.String(length=50), nullable=False),
    sa.Column('corresponding_agency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['corresponding_agency'], ['agencies.agency_name'], ),
    sa.PrimaryKeyConstraint('project_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('agencies')
    # ### end Alembic commands ###
