# Generated by Django 5.2 on 2025-05-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='model_name',
            new_name='agency_name',
        ),
    ]
